FROM apache/airflow:2.8.1-python3.11

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY pyproject.toml /opt/airflow/

RUN pip install --no-cache-dir \
    kafka-python \
    psycopg2-binary \
    pandas \
    requests \
    python-dotenv \
    sqlalchemy \
    apache-airflow-providers-postgres \
    apache-airflow-providers-apache-kafka
